blank_issues_enabled: true
contact_links:
  - name: "\U0001F4F7 Video Conference Mute Issue"
    url: https://github.com/microsoft/PowerToys/issues/6246
    about: Report Bug for the Video Conference Mute utility
  - name: "\U0001F6A8 Microsoft Security Response Center (MSRC)"
    url: https://msrc.microsoft.com/create-report
    about: Report security bugs
  - name: "\U0001F4DA PowerToys user documentation"
    url: https://github.com/microsoft/PowerToys/wiki
    about: Documentation for users of PowerToys utilities
  - name: "\U0001F4DA PowerToys dev documentation"
    url: https://github.com/microsoft/PowerToys/tree/master/doc/devdocs
    about: Documentation for people interested in developing and contributing for PowerToys
 
